### ISSUE TITLE
Selective Permanode

### ISSUE THREAD

**Issue by DaughterOfMars** [iotaledger/chronicle.rs#102]
[Relevant RFC](https://github.com/iotaledger/chronicle-rfcs/blob/selective-permanode/text/0001-selective-permanode.md)

### Problem
Chronicle should be able to indicate specific messages to store and their proof, discarding the rest.

## Proposal
We should be able to implement this via a three step process:

1. Store selected messages. This involves allowing users to inspect incoming messages and pick the ones they wish to keep.
This is basically a naive permanode implementation. Whether a message is selected or not will be passed to the solidifier.
2. Collect non-selected messages and build proof until a milestone references the selected message.
3. Insert the proof chain and mark the milestone as persisted.

In addition, we must store every milestone as a trusted chain.

**Comment by Roy-export** [comment]
This suggestion is similar to issue #40
