### ISSUE TITLE
Remove logger crate in Chronicle-Common and just adopt the Bee logger

### ISSUE THREAD

**Issue by bingyanglin** [iotaledger/chronicle.rs#52]
Need to remove the #[derive(Debug)] for any types which use the logger

**Comment by bingyanglin** [comment]
Current `LoggerConfigBuilder` in [bee-common](https://github.com/iotaledger/bee/blob/master/bee-common/bee-common/src/logger/config.rs#L28) has not `Clone` trait. There will be a problem by just adopting it, because Rust does not allow deriving external traits on external structs.

Either we need to refactory the usage of `LoggerConfigBuilder` in Chronicle, or the `LoggerConfigBuilder` should have the derived `Clone` trait.

**Comment by LouayKamel** [comment]
Closing this for now as we already discussed to settle on the current implementation
