### ISSUE TITLE
API Request limit size is too small

### ISSUE THREAD

**Issue by obany** [iotaledger/chronicle.rs#63]
## Bug description

The API fails if requests are larger than 16384 bytes, this is too small even for the default API request sizes. https://github.com/iotaledger/chronicle.rs/blob/592f9c2dd4f4794f6666a00950028e5b9b446d74/chronicle-api/src/api/router.rs#L48

e.g. default paging size is 255 so you can call `findTransactions` and potentially get 255 hashes in response.

If you then want to perform `getTrytes` on the same set of hashes it will exceed the limit
255 * 81 = 20655 for just the hashes without any of the JSON wrapper (hints etc).

## Version

1.1

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Perform `findTransactions` request on address which has as large number of transactions
2. Request `getTrytes` for the large set of hashes

## Expected behaviour

Should not fail with request too large.

## Actual behaviour

Fails with request too large error.

## Notes

Suggest making the limit much larger.

**Comment by LouayKamel** [comment]
Yes, we are going to push a configurable content-length in future releases, Any desirable default option?

**Comment by obany** [comment]
I would have thought something along the lines of 65536 bytes would be better as a default, this would allow for 500 hashes in a payload with some headroom.
