### ISSUE TITLE
Panic while importing .dmp files

### ISSUE THREAD

**Issue by luca-marchiori** [iotaledger/chronicle.rs#65]
## Bug description

permanode crashed while importing .dmp files.  scylla-server was still running

## Version

- Version:  592f9c2

## Hardware specification

- OS and version:  ubuntu 18.04 LTS
- RAM: 48 GB
- Number of cores: 8  

## Node Settings (delete if not relevant)

What are your node settings? Are you using automatic node management?

- Node settings: 

core_threads = 4

## Steps To reproduce the bug

1.  download full .dmp archive
2.  edit config.toml to point to .dmp files:  
`files = [["/var/lib/dump-backup/6000.dmp", 6000], ["/var/lib/dump-backup/13157.dmp", 13157], `  etc....
3.  `cargo run --example permanode /opt/chronicle.rs/examples/config.toml`

## Expected behaviour

for permanode to finish importing all .dmp files and show:

`[2020-07-11][19:03:59][permanode][INFO] AppStatus: storage is Running, and got registered
[2020-07-11][19:03:59][permanode][INFO] AppStatus: api is Running, and got registered
[2020-07-11][19:03:59][permanode][INFO] AppStatus: broker is Running, and got registered
`

## Actual behaviour

after importing 5 or 6 .dmp files (loaded in chronological order), permanode crashed

## Errors

[backtrace permanode crash.txt](https://github.com/iotaledger/chronicle.rs/files/4933727/backtrace.permanode.crash.txt)

**Comment by LouayKamel** [comment]
The issue is due to typo in `decoder::str` function while decoding `WriteType` error, I will push a fix now.
