### ISSUE TITLE
Dashboard Requirements

### ISSUE THREAD

**Issue by DaughterOfMars** [iotaledger/chronicle.rs#82]
## Description
This issue will track all requirements specific to the Permanode dashboard.

# Requirements

| Requirement                  |              Status             |  Children |
| :------------------------- | :------------------------: | --------- |
| Permanode screen<br><ul><li>Dump file import</li><li>Admin notifications</li></ul> | :new_moon: |  |
| Scylla screen<br><ul><li>Cluster status and metrics</li><li>Cluster management</li></ul> | :new_moon: |  |
| Broker screen<br><ul><li>View / Add / Remove feed sources</li></ul> | :new_moon: |  |
| Generic Actor screen *<br><ul><li>Status</li><li>Name</li><li>Uptime / Downtime</li><li>Pause / Resume / Shutdown</li><li>Links to children apps</li></ul> | :new_moon: |  |
| Message Explorer | 🌕  |  |

\* _Also applies to above screens_

### Timeline
Should be completed in Q2 2021.

**Comment by Alexandcoats** [comment]
The explorer has been integrated with the test node.
