### ISSUE TITLE
Chronicle CLI

### ISSUE THREAD

**Issue by DaughterOfMars** [iotaledger/chronicle.rs#85]
## Description
Chronicle needs some kind of CLI to interact with the running instance until we get a proper dashboard. We should make something simple that can perform the basic functionality an admin will need.

# Tasks

|                Task                  |              Status             |  Children |
| ------------------------- | :------------------------: | --------- |
| Start and stop the app | 🌕 | |
| Rebuild the ring | 🌕  | |
| Add nodes | 🌕  | | 
| List nodes | 🌕  | |
| Add broker mqtt endpoints | 🌕  | | 
| Remove broker mqtt endpoints | 🌕  | | 
| Add broker api endpoints | 🌕  | |
| Remove broker api endpoints | 🌕  | |
| List broker endpoints / mqtt | 🌕  | |
| Archive import | 🌕 | |
| Archive merge | 🌕  | |
| Archive export | 🌕  | #99  |
| Metrics | 🌑 | |

**Comment by Alexandcoats** [comment]
Merge added 93b7c52e1e61d4b292c935aa7c74b3ecaaf2464a
