### ISSUE TITLE
Add handling for critical config changes

### ISSUE THREAD

**Issue by DaughterOfMars** [iotaledger/chronicle.rs#87]
## Description
Some config changes, such as partition config, cannot be safely changed after running the app. We should create a `system` table to track these critical configurations and ensure we do not start the app with a breaking config. Additionally, we should provide a process by which a user can migrate these critical configs if necessary.

# Tasks

|                Task                  |              Status             |  Children |
| ------------------------- | :------------------------: | --------- |
| Design `system` table       | :new_moon:      | |
| Determine critical configs | :new_moon:                     | |
| Integrate table usage into startup logic | :new_moon:   | |
| Design process to migrate configs  | :new_moon:                   | |
| Document migration process somewhere visible for users | :new_moon:                   | |

### Timeline
Post-C2 launch

**Comment by Alexandcoats** [comment]
Startup logic pseudocode:
```
if system_record exists {
  if system_record.critical_configs != loaded_critical_configs {
    exit("Critical configs have been changed! To migrate these configs, refer to <instructions_link>")
  }
} else {
  create system_record
}
...
start_chronicle()
```
