### ISSUE TITLE
Export Archive Files

### ISSUE THREAD

**Issue by DaughterOfMars** [iotaledger/chronicle.rs#99]
### Problem
If logs are missed somehow, but the milestone data exists in the database, there is currently no way to export those milestones to log files.

## Proposal
Chronicle should have the opposite of the Importer, an Exporter which will write a given milestone range to log files from the database. Additionally, the CLI should have a command to request this.

**Comment by Alexandcoats** [comment]
Exporter has been added in `new-backstage` branch as part of a42d23afe813a4849f97c4cb2a8bd7aabb3beac6

**Comment by Alexandcoats** [comment]
Exporter ported to `backstage` branch as part of ac6352242526d32871269d67ffa8ba81a4b3de7d;
